### ISSUE TITLE
random switch to sneak pov

### ISSUE THREAD

**Issue by bannahnah** [gigabit101/Shrink#18] opened 2021-02-26 18:12 UTC
After using the Personal Shrinking Device and reverting back to regular size, we would get random sneak POV regardless of what we're doing. Crouching and un-crouching brings us back to the regular first person POV.  This has never happened prior to using the Personal Shrinking Device.

I'm aware there was another thread that brought this up but it's been a recurring thing and again, this only started after using the Shrinking Device. This has been happening in an Enigmatica 6 server.

**Comment by TheawesomeQ** [comment] 2021-02-28 22:03
This also occurs on a DIrewolf20 dedicated server. See https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/118

**Comment by F0x06** [comment] 2021-03-01 18:28
Yes, same issue is my 1.16.5 modpack.

**Comment by theboo** [comment] 2021-03-04 01:01
This I believe this to be the same bug that was reported in #10 but they did not explain it very well.. I do not have a server to test this on with just shrink installed, but it only happens after using the device at least once. steps to repro can be found here: https://github.com/NillerMedDild/Enigmatica6/issues/1527#issuecomment-790189837

**Comment by AlienXAXS** [comment] 2021-03-04 01:09
Just adding more here:
If the player that is affected by the camera pov issue is shrunk and unshrunk by someone else, the bug goes away until that player shrinks themselves once again.

**Comment by gigabit101** [comment] 2021-03-06 17:33
dupe of #11

**Closed by gigabit101** 2021-03-06 17:33 UTC
